language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "remartins-github" # the key of the org you chose at step #3
    token:
      secure: ${SONAR_TOKEN2}
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

jdk:
  - oraclejdk8

script: 
  - mvn clean install org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
